# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97e4769e91cbf17062d130177d041259cd0c333d44a8517484c41d006814e21f7a3fd5bad05d309d7da548e71c5ebcf3039429c49adc6dd6c0363ba529a76652

test:
  secret_key_base: ae9dfed55554bd8ae0379f35c76b24b8e9b7eea986c123160ffda178a9bbce1a6826ffa33f9b7279c78446473102bd6c1d1cb406e1ec5c940af238458be619b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
